### ISSUE TITLE
Survival Fly

### ISSUE THREAD

**Issue by CruelWinter2** [funkemunky/Iris-Issues#10]
When I fly in survival with essentialsx, I get flagged for bad packets. My server version is Spigot 1.13.2. Essentialsx plugin version is 2.16.0.3. Iris and Atlas are up to date.

**Comment by CruelWinter2** [comment]
To recreate the issue, type /fly when using Essentialsx.

**Comment by funkemunky** [comment]
Please use the proper bug reporting format. However, the reason Im not closing this is because I can recreate it and you gave me enough information.
