### ISSUE TITLE
Teleportation Bypass

### ISSUE THREAD

**Issue by ZakShearman** [funkemunky/Iris-Issues#100]
**Describe the bug**
Bypass when teleporting (doesn't get cancelled)

**Version Information**
- Iris Anticheat Version (Latest is not a version): 
- Atlas Version (Latest is not a version): 1.2-PRE-8
- Bukkit/Spigot Version (Latest is not a version): 1.8.8 Normal Spigot

**Are you using the ViaVersion plugin?**: Yes.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
Video here - https://youtu.be/aAQC5wHtk_c (No idea why it's in 360p, I recorded in 1080p).

So it is detected, but even though I have cancelling on, it is not getting cancelled/doesn't flag enough.

**Comment by FozzieHi** [comment]
This should be fixed in the next update.
