### ISSUE TITLE
LaunchPadPlus

### ISSUE THREAD

**Issue by Foulest** [funkemunky/Iris-Issues#101]
**Describe the bug**
When someone launches off a launch pad with LaunchPadPlus.

**Version Information**
- Iris Anticheat Version (Latest is not a version): 1.9.2
- Atlas Version (Latest is not a version): 1.1.4.1
- Bukkit/Spigot Version (Latest is not a version): 1.12.2 PaperSpigot

**Are you using the ViaVersion plugin?**: Yes I am.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I created a launch pad with /lpcreate
2) I used it
3) I flagged hard for Fly

**Additional context**
https://www.spigotmc.org/resources/launch-pad-plus.8315/

**Comment by FozzieHi** [comment]
I can't add API support for every plugin, you'll have to contact the Developer of LaunchPadPlus about adding support.
