### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Foulest** [funkemunky/Iris-Issues#102]
**Describe the bug**
Iris gives me an internal error doing the command `/iris logs _`.

**Version Information**
- Iris Anticheat Version (Latest is not a version): 1.8.2
- Atlas Version (Latest is not a version): 1.1.4.1
- Bukkit/Spigot Version (Latest is not a version): PaperSpigot 1.12.2

**Are you using the ViaVersion plugin?**: Yes

**Server Logs (Pastebin link)**
https://pastebin.com/raw/CBZgAy2t

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Type `/iris logs _` in chat.

**Comment by FozzieHi** [comment]
I don't see what you expect /iris logs _ to produce? but this has been replaced with an accurate error message.
