### ISSUE TITLE
Aim Pattern B + C false positive

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#103]
**Describe the bug**
When moving around and making sharp turns, you will get a bit of false positives. When just derping or shaking your head, you get A LOT of false positives.

**Version Information**
- Iris Anticheat Version: 1.8.6
- Atlas Version: 1.2
- Bukkit/Spigot Version: Version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Are you using the ViaVersion plugin?**: 
Yes

**Server Logs (Pastebin link)**
My logs do not log the anticheat.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I Shook my head really fast
OR
1) I moved in sharp turns
2) Anticheat said I was hacking

**Screenshots/Video**
https://www.mediafire.com/file/czte2qah0newfik/Minecraft_1.12.2_5_17_2019_4_56_43_PM.mp4/file

**Additional context**
I'm in 1.12 with Optifine.

**Comment by FozzieHi** [comment]
Does this only happen on 1.12? I can't reproduce it on my own server.

**Comment by ghost** [comment]
I have no idea.
