### ISSUE TITLE
Autoclick type A bug (Also b and c)

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#104]
**Describe the bug**
When you are swimming about 3 blocks above a block (just to the point where u can barely reach it) and breaking it, the autoclicker detects you as hacking.

**Version Information**
Iris Anticheat Version: 1.8.7 (Not the latest but was not patched in 1.8.8 according to the changelog)
Atlas Version: 1.2
Bukkit/Spigot Version: Version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Are you using the ViaVersion plugin?**: 
Yes

**Server Logs (Pastebin link)**
N/A

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I went into water
2) I swam steadily around 3 blocks above ice
3) Anticheat went crazy

**Screenshots/Video**
https://www.mediafire.com/file/29d3451820mt3o5/Minecraft_1.12.2_2019-05-29_17-42-53.mp4/file

**Additional context**
I'm on 1.12.2

**Comment by FozzieHi** [comment]
I'll take a look at this, thanks for reporting it!

**Comment by FozzieHi** [comment]
This should now be fixed.
