### ISSUE TITLE
impact speed and criticals bypass

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#105]
Version Information
- Iris Anticheat Version (Latest is not a version): 1.8.8
- Atlas Version (Latest is not a version): whatever the newest version is i forgot the newest version number
- Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?:  yes

not a bug but a bypass impacts speed mode bhop and criticals mode packet bypass

**Comment by lutzseverino** [comment]
You didn't even specify what to do to bypass, please post a video about you bypassing or close the thread.

**Comment by FozzieHi** [comment]
As @JasperWorld said, a video would be nice or an explanation on what module settings you have used.
