### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Flexiboi** [funkemunky/Iris-Issues#106]
**Describe the bug**
Op people getting logged for cheating without them useing a cheat client.

**Version Information**
- Iris Anticheat Version (Latest is not a version): 1.8.8
- Atlas Version (Latest is not a version): 1.2.1-PRE-b2
- Bukkit/Spigot Version (Latest is not a version): 1.8 / 1.8.8

**Are you using the ViaVersion plugin?**: not yet

**Server Logs (Pastebin link)**
Provide the server log of the time the bug occurred.
https://pastebin.com/Zny9GkkC

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Oped me and my friend
2) had a test pvp fight, flyed around etc.
3) got logs that we are cheating

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.
https://www.youtube.com/watch?v=2X1EdMwOpno&feature=youtu.be
https://www.youtube.com/watch?v=4m8FVLFf-L0
https://prnt.sc/nxn1j0

**Comment by lutzseverino** [comment]
You are failing at loading tons of plugins, (basing myself from the pastebin you pasted there) I recommend you check for updates for every plugin or re-download spigot since there is something clearly going on there.

**Comment by FozzieHi** [comment]
This may be an issue with your plugins or server delaying or not performing events, have you tried updating Spigot or fixing some of the errors in Console?
