### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by kermandev** [funkemunky/Iris-Issues#107]
**Describe the bug**

**Version Information**
- Iris Anticheat Version 1.8.9
- Atlas Version 1.3.1
- Bukkit/Spigot Version 1.13.2 Paper 

**Are you using the ViaVersion plugin?**: 
yes
**Server Logs (Pastebin link)**
Provide the server log of the time the bug occurred.
https://pastebin.com/tvjUHWC2
**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) joined
2) spammed console
3) .....

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.

**Additional context**

**Comment by LB45440078L** [comment]
Please close the issue, this console spam message has been fixed by Fozzie with the Latest Iris (1.9.9)  and Atlas 1.4.4
