### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by shastagrande** [funkemunky/Iris-Issues#108]
**Describe the bug**
I get false positives when I go on launchpads and when I sprint.

**Version Information**
- Iris Anticheat Version (Latest is not a version): 1.8.9
- Atlas Version (Latest is not a version): 1.3.1
- Bukkit/Spigot Version (Latest is not a version):  1.8

**Are you using the ViaVersion plugin?**: yes

**Server Logs (Pastebin link)**
Provide the server log of the time the bug occurred.
doesn't log alerts

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I jumped down the pit in my kitpvp server
2) I sprinted and got alerts of me speed hacking
3) I went on the launchpad and got alerts of flight

**Screenshots/Video**
https://youtu.be/s488sykvRY8

**Additional context**

**Comment by FozzieHi** [comment]
You'll need to contact the developer to cancel Iris cheat events using the API.
