### ISSUE TITLE
Many WARNs in the Console

### ISSUE THREAD

**Issue by LB45440078L** [funkemunky/Iris-Issues#110]
**Describe the bug**
I'm getting many long errors from the console, I'm not sure that it's caused by your plugin but I haven't been able to find out.

**Version Information**
- Iris Anticheat Version 1.9.5
- Atlas Version 1.3.1
- Spigot jar 1.11.2

**Are you using the ViaVersion plugin?**: 
Using ViaVersion 2.1.2

**Server Logs (Pastebin link)**
I CAN'T PASTE THE ENTIRE LOG AS IT'S TOO LONG AND IT'S BASICALLY FLOODING THE CONSOLE WITH INSANE LONG ERRORS AND MAKING MY RAM GO INSANE, THE LOG OF 10 minutes is like 14000KB OF RAW TEXT. THIS IS A PARTIAL ONE
https://pastebin.com/Xw6ZbJQq
AND I UPLOADED ON FIREFOX SEND THE ENTIRE LOG FILE (needs a log viewer)
https://send.firefox.com/download/812c9aef947811b9/#R4YgkVdtxzuQN8dFe1a6Zw

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I started the server
2) Errors start when player are in the server 
3) I don't really know what to do 

**Screenshots/Video**
There are no issues presenting in-game.

**Additional context**
Plugin list here:

**Comment by LB45440078L** [comment]
Just to be sure I've done several tests. The issue is presenting even in localhost with few plugins:
Localhost info:
Spigot-1.11.2 build LATEST (API version 1.11.2-R0.1-SNAPSHOT)
Plugins:
- Atlas 1.3.7 
- Iris 1.9.8 (latest custom version by Fozzie provided Via Discord)
--------------
UPDATED:
Console spam stopped, but getting 1 error on boot and hack checks not working and also many commands.
log:
https://pastebin.com/bBq1efc7

**Comment by FozzieHi** [comment]
Have you tried the latest version?
