### ISSUE TITLE
Step B False Flag

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#111]
Describe the bug
Step B False Flag

Version Information
- Iris Anticheat Version (Latest is not a version): 1.9.5
- Atlas Version (Latest is not a version): 1.3.1
- Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:
1) i went up alot of blocks
2) then jumped on slime at the bottom
3) then it falsed Step B

Screenshots/Video
https://streamable.com/jt64y

Additional context
idk

**Comment by FozzieHi** [comment]
Fixed.
