### ISSUE TITLE
Speed A False Flag

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#112]
Describe the bug

Version Information
- Iris Anticheat Version (Latest is not a version): 1.9.5
- Atlas Version (Latest is not a version): 1.3.1
- Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:
1) put alot of ice down in a long line
2) put slabs on top of the ice
3) then sprint and jump on it then it will false Speed A

Screenshots/Video
https://streamable.com/8137j

Additional context
idk

**Comment by FozzieHi** [comment]
Fixed.
