### ISSUE TITLE
Step A False Flag

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#114]
Describe the bug

Version Information

Iris Anticheat Version (Latest is not a version): 1.9.5
Atlas Version (Latest is not a version): 1.3.1
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:
Put a bed on the ground then walk onto it and it will False Step A

Screenshots/Video
https://streamable.com/ip1ts

Additional context
idk

**Comment by FozzieHi** [comment]
Fixed.
