### ISSUE TITLE
LiquidWalk A And Speed D False Flag

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#115]
Describe the bug
LiquidWalk A And Speed D False Flag
Version Information

Iris Anticheat Version (Latest is not a version): 1.9.5
Atlas Version (Latest is not a version): 1.3.1
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:
Place Water down like a hill in the video then go down it and it will false LiquidWalk A And Speed D

Screenshots/Video
https://streamable.com/bx363

Additional context
idk

**Comment by FozzieHi** [comment]
Fixed Speed D, I'll look into Liquid Walk A.
