### ISSUE TITLE
Speed A False Flag

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#116]
Describe the bug
Speed A False Flag
Version Information

Iris Anticheat Version (Latest is not a version): 1.9.5
Atlas Version (Latest is not a version): 1.3.1
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:
i went on ice then jumped off of it like on the edge watch the video sense im not the best explainer 

Screenshots/Video
https://streamable.com/366br

Additional context
idk

**Comment by FozzieHi** [comment]
I fixed this earlier today.
