### ISSUE TITLE
NoSlowDown False Flag

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#117]
Describe the bug
NoSlowDown False Flag
Version Information

Iris Anticheat Version (Latest is not a version): 1.9.5
Atlas Version (Latest is not a version): 1.3.1
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:
add essentials to your server then do /speed 3 or higher then block with a sword

Screenshots/Video
https://streamable.com/bjyqs

Additional context
idk

**Comment by FozzieHi** [comment]
I plan to completely remake NoSlowdown.
