### ISSUE TITLE
Flight E False Flag

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#118]
Describe the bug
Flight E False Flag
Version Information

Iris Anticheat Version (Latest is not a version): 1.9.5
Atlas Version (Latest is not a version): 1.3.1
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:

put ladders on the side of blocks then put another one 2 blocks up then go up them and it will false Flight E

Screenshots/Video
https://streamable.com/zmnez

Additional context
idk

**Comment by FozzieHi** [comment]
Fixed.
