### ISSUE TITLE
Flight E False Flag v2

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#119]
Describe the bug
Flight E False Flag v2
Version Information

Iris Anticheat Version (Latest is not a version): 1.9.5
Atlas Version (Latest is not a version): 1.3.1
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:

put down a brewing stand then walk on and off of it

Screenshots/Video
https://streamable.com/2ykl2

Additional context
idk

**Comment by FozzieHi** [comment]
Doesn't seem to happen on my server, can you try using 1.9.6?

**Comment by ghost** [comment]
> Doesn't seem to happen on my server, can you try using 1.9.6?

can you whitelist me on the offical test server i want to see if it falses on there sense the newer version is on there my ign is marshmallowkush

**Comment by FozzieHi** [comment]
done
