### ISSUE TITLE
VCLIP SHIT

### ISSUE THREAD

**Issue by True-cc** [funkemunky/Iris-Issues#12]
**Describe the bug**

**Version Information**
- Iris Anticheat Version - version
- Atlas Version - of test
- Bukkit/Spigot Version - server

**Server Logs**
Provide the server log of the time the bug occurred.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Well, in liquidbounce, I put the VClip setting to FLAG and not TELEPORT so it does shit.

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.

https://youtu.be/weMybncycoc

**Additional context**
NOT NORMAL VCLIP!!!!!!!!!!!!! It's the flagggggg type thing vclip that tp's u up then back down.
Btw, I'm Shoghi Simon. Yes, that person who said `DO THE AN ANTI VCLIP AND HCLIP SHIT` and then u did a silly name for it. It was cute. 👍

**Comment by True-cc** [comment]
Video now available. Sorry about that.

**Comment by funkemunky** [comment]
This has been fixed, thanks for the report.
