### ISSUE TITLE
Speed D False Flag

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#120]
Describe the bug
Speed D False Flag
Version Information

Iris Anticheat Version (Latest is not a version): 1.9.5
Atlas Version (Latest is not a version): 1.3.1
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:

Put on depthstrider 3 boots and put on speed 2 then go in the water and it falses speed D

Screenshots/Video
https://streamable.com/qs1pl

Additional context
idk

**Comment by FozzieHi** [comment]
Fixed.
