### ISSUE TITLE
Step B False Flag

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#122]
Describe the bug
Step B False Flag
Version Information

Iris Anticheat Version (Latest is not a version): 1.9.5
Atlas Version (Latest is not a version): 1.3.1
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:
effect yourself with jumpboost 2 then jump on the sides in the vines but do it where it doesn't slow you down where you fall like inside of the vines but in the very sides where you dont get slowdowned when you fall

Screenshots/Video
https://streamable.com/litw7

Additional context
idk

**Comment by FozzieHi** [comment]
Fixed.
