### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by OPm0vest** [funkemunky/Iris-Issues#124]
**Describe the bug**
Recently, I had just flagged 2 times false Badpacket (Type C).

**Version Information**
- Iris Anticheat Version (Latest is not a version): 1.9.8
- Atlas Version (Latest is not a version): 1.3.7
- Bukkit/Spigot Version (Latest is not a version): 1.8.8

**Are you using the ViaVersion plugin?**:  Yes.

**Server Logs (Pastebin link)**
Provide the server log of the time the bug occurred.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Ping bad - Malaysia
2) Jump of a ~25 blocks height and got tp back a few blocks after i had jump.

**Screenshots/Video**
None.

**Additional context**
None.

**Comment by FozzieHi** [comment]
How do you jump 25 blocks legitimately?
