### ISSUE TITLE
NullPointerException. + Incompatibility.

### ISSUE THREAD

**Issue by LB45440078L** [funkemunky/Iris-Issues#125]
**Describe the bug**
When the plugin is enabled something like every 2 minutes the console prints out longs error which appear to be from Atlas. 

**Version Information**
- Iris Anticheat Version (1.9.9-FIX): 
- Atlas Version (1.4.4): 
- PaperSpigot Version (1.12.2-LatestBuild): 

**Are you using the ViaVersion plugin?**: 

I am using ViaVersion v2.1.3
and ViaBackwards 3.0.0-SNAPSHOT

**Server Logs (Pastebin link)**
logs of the error
https://pastebin.com/gnjEpz0Z

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
I boot server, and started to notice frequent NPE.

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.

**Additional context**
Iris 1.9.9 and 1.9.9-FIX, are NOT compatible with the new Atlas versions (1.4.5 , 1.4.6). They seem to break Iris.

**Comment by FozzieHi** [comment]
This should be fixed in the next version.
