### ISSUE TITLE
NoFall + Flight(B) + Step (B). [FP]

### ISSUE THREAD

**Issue by LB45440078L** [funkemunky/Iris-Issues#126]
**Describe the bug**
Player generate false flags when going down a hole

**Version Information**
- Iris Anticheat Version 1.9.9-FIX
- Atlas Version Atlas 1.4.4
- PaperSpigot 1.12.2

**Are you using the ViaVersion plugin?**: 
Using ViaVersion v2.1.3 + ViaBackwards 3.0.0-SNAPSHOT-

**Server Logs (Pastebin link)**
log not require as nothing particular was occurring in the console, except for those Atlas NullPointerException which I've already reported in a different Issue.

**How to re-create**
Create a hole in the ground, possibly more than 80 blocks. Jump in it, and 2/3 times you'll get stuck in midair. False flags will start with a NoFall positive check, then add Flight(B) , and sometimes Step(B). 

Tutorial:
https://www.youtube.com/watch?v=x89VtVi97Qk

**Additional context**
This is easy to replicate

**Comment by FozzieHi** [comment]
Fixed.
