### ISSUE TITLE
Speed B False Flag (this false was fixed but it falses again now idk why)

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#127]
Describe the bug
Speed B False Flag
Version Information

Iris Anticheat Version (Latest is not a version): 1.9.9
Atlas Version (Latest is not a version): 1.4.4
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:
put a piston behind you on ice then put string in front so when you run you hit the string then it bootsts you on the ice and it will false speed B watch the video to see it

Screenshots/Video
https://streamable.com/as14b

Additional context
this bug was fixed but all of a sudden it falses again idk why

**Comment by FozzieHi** [comment]
I do not provide support for users who use leaked versions of the plugin, especially as I cannot reproduce this bug. If you buy the plugin and it is still an issue then I will look into it further.
