### ISSUE TITLE
Liquidwalk A B False Flag

### ISSUE THREAD

**Issue by ghost** [funkemunky/Iris-Issues#130]
Describe the bug
Liquidwalk A B False Flag

Version Information
- Iris Anticheat Version (Latest is not a version): 
- Atlas Version (Latest is not a version): 
- Bukkit/Spigot Version (Latest is not a version): 

Are you using the ViaVersion plugin?: No

Server Logs (Pastebin link)

How to re-create
Steps:
1) I was just sprinting and went into the water like in the video and for some reason i falsed Liquidwalk A and B

Screenshots/Video
https://streamable.com/nqqbr

Additional context
Idk

**Comment by FozzieHi** [comment]
Resubmit the form with it filled out correctly.
