### ISSUE TITLE
Iris/Atlas spamming console and making the server have lag spikes

### ISSUE THREAD

**Issue by DylanCoding** [funkemunky/Iris-Issues#131]
**Describe the bug**
The console is being spammed when using Iris/Atlas.

**Version Information**
- Iris Anticheat Version (Latest is not a version):  2.0.0
- Atlas Version (Latest is not a version): 1.4.6
- Bukkit/Spigot Version (Latest is not a version):  aSpigot - v2.1.1

**Are you using the ViaVersion plugin?**: Nope

**Server Logs (Pastebin link)**
https://pastebin.com/raw/75E0aEw7

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I did nothing but fly around in creative.
2) It also occurs when I change worlds

**Screenshots/Video**

**Additional context**
It never used to happen, but when I reach over maybe 20/30 players it starts to generate lag spikes. I have tested it without Atlas or Iris implemented and no lag spikes.

**Comment by LB45440078L** [comment]
Yo so it's not only me

**Comment by SkyLicks** [comment]
SAME ^. Its only when there are at least 20-30 players on.

**Comment by FozzieHi** [comment]
Fixed.
