### ISSUE TITLE
[False Positive] Speed A Elytra False Positive

### ISSUE THREAD

**Issue by SkyLicks** [funkemunky/Iris-Issues#132]
**Describe the bug**
This bug causes the Speed A event to trigger when using an elytra. Simply spam the spacebar on ground (as you will see in a below video) to trigger this false positive.

**Version Information**
- Iris Anticheat Version (Latest is not a version):  2.0.0
- Atlas Version (Latest is not a version): 1.4.6
- Bukkit/Spigot Version (Latest is not a version): spigot-1.12.2

**Are you using the ViaVersion plugin?**: Yes [with Viabackwards]

**Server Logs (Pastebin link)**
https://pastebin.com/Mdrx4GGs

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Equip an elytra
2) Spam spacebar as you sprint across any flat terrain.

**Screenshots/Video**
https://youtu.be/hQUbEVJm6Mg

**Additional context**

**Comment by FozzieHi** [comment]
Fixed.
