### ISSUE TITLE
[False Positive] Step B Elytra & Firework Rocket

### ISSUE THREAD

**Issue by SkyLicks** [funkemunky/Iris-Issues#133]
**Describe the bug**
This bug triggers the Step B event when a fireworks rocket is used in conjunction with the elytra to boost.

**Version Information**
- Iris Anticheat Version (Latest is not a version): 2.0.0
- Atlas Version (Latest is not a version): 1.4.6
- Bukkit/Spigot Version (Latest is not a version): spigot-1.12.2

**Are you using the ViaVersion plugin?**: Yes [with Via backwards]

**Server Logs (Pastebin link)**
https://pastebin.com/Mdrx4GGs

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I equiped an elytra
2) I activated the elytra
3) I looked up and right click the firework rocket to use it and boost myself

**Screenshots/Video**
https://youtu.be/_rU5jkTIGrc

**Additional context**

**Comment by FozzieHi** [comment]
Fixed.
