### ISSUE TITLE
[False Positive] Flight B Taking of Elytra Mid Air

### ISSUE THREAD

**Issue by SkyLicks** [funkemunky/Iris-Issues#134]
**Describe the bug**
If you are high up in the air with an elytra, and then you take of your elytra mid air, it causes a Flight B false positive.

**Version Information**
- Iris Anticheat Version (Latest is not a version): 2.0.0
- Atlas Version (Latest is not a version): 1.4.6
- Bukkit/Spigot Version (Latest is not a version): spigot-1.12.2

**Are you using the ViaVersion plugin?**: Yes [With viabackwards]

**Server Logs (Pastebin link)**
Version Information

Iris Anticheat Version (Latest is not a version): 2.0.0
Atlas Version (Latest is not a version): 1.4.6
Bukkit/Spigot Version (Latest is not a version): spigot-1.12.2
Are you using the ViaVersion plugin?: Yes [with Via backwards]

Server Logs (Pastebin link)
https://pastebin.com/Mdrx4GGs

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Equip an elytra
2) Either jump of from a high hill or use fireworks rocket to get high up in the air with the elytra
3) Take of your elytra mid flight

**Screenshots/Video**
https://youtu.be/_5YuF3JFoow

**Additional context**

**Comment by FozzieHi** [comment]
Fixed.
