### ISSUE TITLE
[False Positive] Flight B and Nofall Swimming FP

### ISSUE THREAD

**Issue by SkyLicks** [funkemunky/Iris-Issues#136]
**Describe the bug**
This bug causes false positives when swimming in water.

**Version Information**
- Iris Anticheat Version (Latest is not a version): 2.0.0
- Atlas Version (Latest is not a version): 1.4.6
- Bukkit/Spigot Version (Latest is not a version): spigot-1.12.2 

**Are you using the ViaVersion plugin?**: Yes [with Viabackwards]

**Server Logs (Pastebin link)**
https://pastebin.com/ZyVF4LWL

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Go in the water
2) Move around
3) Particularly it appears usually when swimming up, this false positive appears

**Screenshots/Video**
https://youtu.be/t6eYGSflW0E

**Additional context**

**Comment by LB45440078L** [comment]
Sorry.
