### ISSUE TITLE
[FP] Nofall + Flight (B) WATER ISSUES

### ISSUE THREAD

**Issue by LB45440078L** [funkemunky/Iris-Issues#137]
#136 **Describe the bug**
Issues when moving underwater / swimming / moving in the water in general.

**Version Information**
- Iris Anticheat Version 2.0.0
- Atlas Version 1.4.6
- PaperSpigot 1.12.2 (Latest build)

**Are you using the ViaVersion plugin?**: 
Viaversion 2.1.3, ViaBackwards v3.0.0-SNAPSHOT.

**Server Logs (Pastebin link)**
NullPointerException on player logins.
https://pastebin.com/wrNnNsnx

**How to re-create**
VIDEO: https://youtu.be/A4IIvCa0uM0

**Screenshots/Video**
https://youtu.be/A4IIvCa0uM0

**Additional context**
Player can't move properly in water, they get kicked.

**Comment by SkyLicks** [comment]
*cough*
https://github.com/funkemunky/Iris-Issues/issues/136

**Comment by FendiTony777** [comment]
#136

**Comment by FozzieHi** [comment]
Fixed.
