### ISSUE TITLE
[FP] Reach(C) 

### ISSUE THREAD

**Issue by LB45440078L** [funkemunky/Iris-Issues#140]
**Describe the bug**
Iris anticheat generates false positives for 

**Version Information**
- Iris Anticheat Version 2.0.0
- Atlas Version 1.4.6
- PaperSpigot 1.12.2

**Are you using the ViaVersion plugin?**: 
ViaVersion v2.1.3 , ViaBackwards v3.0.0-SNAP

**Server Logs (Pastebin link)**
no

**How to re-create**
Take a lot of mobs, as in video, and hit them fast for a long time. This happens usually on mob farms.
**Screenshots/Video**
https://youtu.be/dLLV6l8D8o0

**Additional context**
Running OldCombatMechanics.
This issue gets really bad when weapons have Sweeping Edge enchantment.

**Comment by FozzieHi** [comment]
Should be fixed.
