### ISSUE TITLE
Server freeze

### ISSUE THREAD

**Issue by DeWilX** [funkemunky/Iris-Issues#142]
**Describe the bug**
Huge spam in console.

**Version Information**
- Iris Anticheat Version (Latest is not a version): 2.0.1
- Atlas Version (Latest is not a version): 1.4.7 
- Bukkit/Spigot Version (Latest is not a version): CraftBukkit version git-TacoSpigot-bf023c7d (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**Are you using the ViaVersion plugin?**: 

**Server Logs (Pastebin link)**
https://pastebin.com/tgHwsBux

**How to re-create**
When player kills players.

**Comment by FozzieHi** [comment]
Yeah, I'm reverting some things in the new update.
