### ISSUE TITLE
[FP] Bad Packet (C) Elytra False Positive

### ISSUE THREAD

**Issue by SkyLicks** [funkemunky/Iris-Issues#143]
**Describe the bug**

More Elytra false positives. This one involves firework rockets too.

**Version Information**
- Iris Anticheat Version (Latest is not a version): 2.0.2
- Atlas Version (Latest is not a version): 1.4.6
- Bukkit/Spigot Version (Latest is not a version): spigot-1.12 (using waterfall)

**Are you using the ViaVersion plugin?**: Yes with viabackwards

**Server Logs (Pastebin link)**
Provide the server log of the time the bug occurred.
https://pastebin.com/pe2TLwMd

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I equipped an elytra
2) I used firework rockets to boost myself STRAIGHT UP.
3) I got the Bad Packet (C) false positive
4) Then I used fireworks rockets on an elytra in the water.
5) Also got the Bad Packet (C) false positive

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.
https://youtu.be/0ePNrYl-Bc4

**Additional context**

**Comment by FozzieHi** [comment]
Fixed.
