### ISSUE TITLE
[Bypass] Basic Autoclickers not getting detected

### ISSUE THREAD

**Issue by SkyLicks** [funkemunky/Iris-Issues#146]
**Describe the bug**

Im using a basic auto clicker (with no fancy random clicking). It clicks consistently but Iris doesnt detect it.

**Version Information**
- Iris Anticheat Version (Latest is not a version): 2.0.2
- Atlas Version (Latest is not a version): 1.4.6
- Bukkit/Spigot Version (Latest is not a version): spigot-1.12.2

**Are you using the ViaVersion plugin?**: Yes

**Server Logs (Pastebin link)**
Provide the server log of the time the bug occurred.
https://pastebin.com/pef7xZ99

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Download this autoclicker: https://sourceforge.net/projects/orphamielautoclicker/
2) Set it to any speed (thats not CRAZY high)
3) Iris will not detect it

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.
https://youtu.be/WsHEfsSgCEU

**Additional context**

I know some anti cheats have a consistency check where is someone is clicking the same speed for an x amount of time its a very good indicator they have an auto clicker.

**Comment by FozzieHi** [comment]
What CPS are you clicking at? Iris doesn't detect low CPS click speeds as it could false flag consistency checks.

**Comment by SkyLicks** [comment]
Ive tested speeds as high as 16 CPS

**Comment by FozzieHi** [comment]
Then they should flag, can you try them on my test server? `iris.fozzie.space`

**Comment by FozzieHi** [comment]
The checks are slow though, to prevent false positives.
