### ISSUE TITLE
Iris Speed Fly Killaura ext.

### ISSUE THREAD

**Issue by True-cc** [funkemunky/Iris-Issues#15]
**Describe the bug**
SPEED FLY AND KILLAURA

**Version Information**
- Iris Anticheat Version - test
- Atlas Version - server
- Bukkit/Spigot Version - version

**Server Logs**
N/A TEST SREVRE!!!!
**How to re-create**
1) Hacks.

**Screenshots/Video**
https://youtu.be/Hc4tCuJY3Cw
**Additional context**
Ur anticheat is shit and make a clipadoodle check.
Speed is: 4 times every second, you tp 5 blocks in front of you. Fly is: every tick, you teleport 5 blocks above you, can clip through ceilings.

**Comment by funkemunky** [comment]
Thanks for the report, this has been fixed.
