### ISSUE TITLE
Speed A F D And Flight D False Flag

### ISSUE THREAD

**Issue by coolpvpv** [funkemunky/Iris-Issues#153]
Describe the bug
Speed A F D And Flight D False Flag
Version Information

Iris Anticheat Version (Latest is not a version): 2.0.6
Atlas Version (Latest is not a version): 1.4.6
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:

put down ice like in the video sprint and jump on it and it will False Speed A F D and Flight D

Screenshots/Video
https://streamable.com/towm0
Additional context
idk

**Comment by FozzieHi** [comment]
I have told you this before, I do not support leaked versions of the plugin especially as I cannot reproduce most of these issues.
