### ISSUE TITLE
Speed D False Flag

### ISSUE THREAD

**Issue by coolpvpv** [funkemunky/Iris-Issues#154]
Describe the bug

Version Information

Iris Anticheat Version (Latest is not a version): 2.0.6
Atlas Version (Latest is not a version): 1.4.6
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:

put down pistons and the redstone like in the video then run at it and when you get glitched in it you will False Speed D

Screenshots/Video
https://streamable.com/vrgni
Additional context
idk

**Comment by FozzieHi** [comment]
I have told you this before, I do not support leaked versions of the plugin especially as I cannot reproduce most of these issues.
