### ISSUE TITLE
Flight G False Flag

### ISSUE THREAD

**Issue by coolpvpv** [funkemunky/Iris-Issues#156]
Describe the bug
Flight G False Flag
Version Information

Iris Anticheat Version (Latest is not a version): 2.0.6
Atlas Version (Latest is not a version): 1.4.6
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:

put cobwebs in the air like in the video then sprint and jump in them and you will False Flight G

Screenshots/Video
https://streamable.com/3j7kb
Additional context
idk

**Comment by FozzieHi** [comment]
I have told you this before, I do not support leaked versions of the plugin especially as I cannot reproduce most of these issues.
