### ISSUE TITLE
Reach D False Flag

### ISSUE THREAD

**Issue by coolpvpv** [funkemunky/Iris-Issues#157]
Describe the bug
Reach D False Flag
Version Information

Iris Anticheat Version (Latest is not a version): 2.0.6
Atlas Version (Latest is not a version): 1.4.6
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:

if your riding a horse or pig and hit something it will flag Reach D and when you hover over the Reach D alerts it says im like hitting from 40-42 blocks away which idk why it does that but it does

Screenshots/Video
https://streamable.com/3vwwg
Additional context
idk

**Comment by FozzieHi** [comment]
I have told you this before, I do not support leaked versions of the plugin especially as I cannot reproduce most of these issues.
