### ISSUE TITLE
Speed E False Flag

### ISSUE THREAD

**Issue by coolpvpv** [funkemunky/Iris-Issues#158]
Describe the bug

Version Information

Iris Anticheat Version (Latest is not a version): 2.0.6
Atlas Version (Latest is not a version): 1.4.6
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:

put water down like in the video enchant your boots with depthstrider 3 then sprint down the water and it will false Speed E

Screenshots/Video
https://streamable.com/0cqrj
Additional context
idk

**Comment by FozzieHi** [comment]
I have told you this before, I do not support leaked versions of the plugin especially as I cannot reproduce most of these issues.
