### ISSUE TITLE
Badpackets C False Flag

### ISSUE THREAD

**Issue by coolpvpv** [funkemunky/Iris-Issues#160]
Describe the bug
Badpackets C False Flag
Version Information

Iris Anticheat Version (Latest is not a version): 2.0.6
Atlas Version (Latest is not a version): 1.4.6
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:

just pearl down on slabs like in the video and it will false Badpackets c reason why i have no idea

Screenshots/Video
https://streamable.com/8r8xb
Additional context
idk

**Comment by FozzieHi** [comment]
I have told you this before, I do not support leaked versions of the plugin especially as I cannot reproduce most of these issues.

**Comment by coolpvpv** [comment]
> I have told you this before, I do not support leaked versions of the plugin especially as I cannot reproduce most of these issues.

its not a leaked version but ok

**Comment by FozzieHi** [comment]
Then what's your Spigot name?
