### ISSUE TITLE
LiquidWalk B A Speed A F And C False Flag

### ISSUE THREAD

**Issue by coolpvpv** [funkemunky/Iris-Issues#161]
Describe the bug
LiquidWalk B A Speed A F And C False Flag
Version Information

Iris Anticheat Version (Latest is not a version): 2.0.6
Atlas Version (Latest is not a version): 1.4.6
Bukkit/Spigot Version (Latest is not a version): 1.8.8

Are you using the ViaVersion plugin?: no

Server Logs (Pastebin link)

How to re-create
Describe in detail how we can re-create this bug.
Steps:

Get essentials then do /speed 10 and just swim in the water and it will false LiquidWalk B A Speed A F And C

Screenshots/Video
https://streamable.com/r27h4
Additional context
idk

**Comment by FozzieHi** [comment]
I have told you this before, I do not support leaked versions of the plugin especially as I cannot reproduce most of these issues.
