### ISSUE TITLE
Flight False Positives 

### ISSUE THREAD

**Issue by OPm0vest** [funkemunky/Iris-Issues#162]
Describe the bug
Recently, I had just flagged 2 times false Badpacket (Type C).

Version Information

Iris Anticheat Version (Latest is not a version): 1.9.8
Atlas Version (Latest is not a version): 1.3.7
Bukkit/Spigot Version (Latest is not a version): 1.8.8
Are you using the ViaVersion plugin?: Yes.

Server Logs (Pastebin link)
Provide the server log of the time the bug occurred.

How to re-create
Describe in detail how we can re-create this bug.
Steps:

Ping bad - Malaysia
Jump from a ~25 blocks height and got 
Got tp back by iris a few blocks up when falling after i had jump.
Screenshots/Video
None.

Additional context
None.

**Comment by SkyLicks** [comment]
Not my place to comment but...

You are using a pretty outdated version of the anticheat and giving very little / limited information.

A video and your server logs will be useful.
