### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by MineFriend** [funkemunky/Iris-Issues#18]
iris version : 1.5.3.1
atlas version : 1.0.7

https://pastebin.com/yR6EvWMP

**Comment by MineFriend** [comment]
another errors: When the hitbox limit is exceeded, the following command is not executed
even when you exceed killaura (type b) that is, the command is executed for the first time but if the player returns but is no longer executed the command once the limit is exceeded (and so the violations can also arrive x700 + )

**Comment by funkemunky** [comment]
Fixed for the next update.
