### ISSUE TITLE
Reload error

### ISSUE THREAD

**Issue by JasperWorld** [funkemunky/Iris-Issues#19]
**Describe the bug**
When reloading, I get this massive error on console, default config, I just changed the prefix.

**Version Information**
- Iris Anticheat Version: 1.5.3.1
- Atlas Version: 1.0.7
- Bukkit/Spigot Version: 1.8.8

**Server Logs**
https://hastebin.com/gamituroka.md

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Install plugin
2) Reload
3) Done? I don't know if its related to the prefix

**Comment by funkemunky** [comment]
Does this affect Iris's function in any way?

**Comment by JasperWorld** [comment]
Yes,the plugin is still there, but it doesn't reload the things I've set in the menu, (or even sometimes it just stops working)

**Comment by funkemunky** [comment]
Thanks for the report, this has been fixed in the latest update.
