### ISSUE TITLE
Criticals Type A ff

### ISSUE THREAD

**Issue by Vantrex** [funkemunky/Iris-Issues#20]
**Describe the bug**

**Version Information**
- Iris Anticheat Version: 1.5.4
- 1.0.7
- Spigot 1.8.8

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) place some slabs like this: http://prntscr.com/mdz5xb
2) walk over the slabs and hit a player

**Comment by funkemunky** [comment]
Thanks for the report, this will be fixed for the next update. I will let you know when the fix is confirmed.

**Comment by funkemunky** [comment]
This has been fixed in the latest update, appreciate the report.
