### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by wulfwuud** [funkemunky/Iris-Issues#21]
**Describe the bug**
server freezes after launch

**Version Information**
- latest
- latest
- guess latest 1.12.2

**Server Logs**
https://i.imgur.com/E3ffifO.png

**How to re-create**
Start a server

**Screenshots/Video**
https://i.imgur.com/E3ffifO.png

**Additional context**
hurr durr

**Comment by funkemunky** [comment]
This has been fixed for the next update, thanks for the report.
