### ISSUE TITLE
Killaura (Type G) False Flags!

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#23]
**Describe the bug**

**Version Information**
- Iris Anticheat Version: Official test server!
- Atlas Version: Official test server!
- Bukkit/Spigot Version: Official test server!

**Server Logs**
I don't have the logs because that server is not mine.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Attack while jumping

**Screenshots/Video**
https://www.youtube.com/watch?v=e48ydU07eaU&feature=youtu.be

**Additional context**
No.

**Comment by PiiSaba** [comment]
I tested with BLC and 1.8.9 Vanilla.

**Comment by funkemunky** [comment]
Thank you for the report, I believe this has been fixed for the next update. I will let you know and close the issue when I test to make sure.

Right now I am using my phone as a hotspot, so testing may not be totally accurate.

**Comment by PiiSaba** [comment]
It hasn't fixed it.
And I found another false flags.
https://www.youtube.com/watch?v=RfcAoIB3yyc&feature=youtu.be
Critical: 0:53 ~
Timer and Hitbox: 2:52 ~

I think that these ff were caused by server lag/client lag.

**Comment by funkemunky** [comment]
I will continue to do more testing. I believe I have fixed the Hitbox issue in the latest update. Timer, however, I believe I have fixed but the issue was found after I released the new update.

**Comment by PiiSaba** [comment]
The KillAura (Type G) has not fixed yet.

**Comment by funkemunky** [comment]
I have discovered a potential cause for the bug and remedied that it. I will test it when I'm home if the bug is fixed and let you know.

**Comment by funkemunky** [comment]
This has been fixed for the next update.
