### ISSUE TITLE
Server Crash without a reason 

### ISSUE THREAD

**Issue by Vantrex** [funkemunky/Iris-Issues#24]
**Describe the bug**
Random Server Crash

**Version Information**
- Iris: latest
- Atlas: latest
- Spigot: 1.8.8 (custom, but we did not modify the packet system)

**Server Logs**
https://hastebin.com/efabutolik.md

**How to re-create**
idk tbh, it happend twice now (when a player joins)

**Additional context**
Could it be because of ProtocolSupport? I let my players join with 1.7 on a 1.8.8 server.

**Comment by funkemunky** [comment]
No, I do not think it is because of ProtocolSupport. Thanks for letting me know, I will get this fixed ASAP. I have an idea as to what might be causing it.

Also, is this custom spigot a fork of PaperSpigot, TacoSpigot, or anything else? Please let me know.

**Comment by Vantrex** [comment]
its a custom spigot fork (not paper or taco) & the only thing we changed is the kb + pots

**Comment by funkemunky** [comment]
Has this been fixed in the latest update?
