### ISSUE TITLE
Bug Report ( 500+ Errors ) Server Crashes

### ISSUE THREAD

**Issue by GLOCK1337** [funkemunky/Iris-Issues#25]
**Describe the bug**

**Version Information**
- Iris Anticheat Version - lastest
- Atlas Version - lastest
- Bukkit/Spigot Version - exoSpigot

**Server Logs**
https://hastebin.com/ahoronomuc.rb

**How to re-create**
when i start the server everything is okay after everything loads its starts spaming errors every second
https://hastebin.com/ahoronomuc.rb

**Screenshots/Video**
https://hastebin.com/ahoronomuc.rb

**Additional context**
Im getting alot of errors every second and after that the server crashes..

**Comment by funkemunky** [comment]
Hello, I am unsure as tow hat the "latest" version is. You must put in the actual version number before I can help you, as information is limited otherwise.

**Comment by funkemunky** [comment]
Thanks for the report, this has been fixed in the latest update.
