### ISSUE TITLE
Killaura and NoFall. Maybe crits?

### ISSUE THREAD

**Issue by True-cc** [funkemunky/Iris-Issues#27]
**Describe the bug**

**Version Information**
- Iris Anticheat Version - on
- Atlas Version - test
- Bukkit/Spigot Version - server

**Server Logs**
on
test
server

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I made the nofall noground. Ez bypass.
2) Killaura really slow turn speeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeed.

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.
https://youtu.be/98ZoiRVlpQE https://youtu.be/98ZoiRVlpQE https://youtu.be/98ZoiRVlpQE https://youtu.be/CsKbCdzkNZg
**Additional context**
REALLY SLOW TURN SPEEEEEED for killaura and 50% failrate. Killaura bypass

**Comment by funkemunky** [comment]
I appreciate the report, I'm looking into now.

**Comment by funkemunky** [comment]
I'm just going to mention if someone were to use a killaura with a really slow turn speed and a 50% failrate, even I could easily beat the shit out of them in a fight.

**Comment by funkemunky** [comment]
Fixed in the 1.6.2 and 1.6.1 update of Iris. Thanks for the report!
