### ISSUE TITLE
I can't use the anticheat because of the intensive lag

### ISSUE THREAD

**Issue by R3XET** [funkemunky/Iris-Issues#28]
**Describe the bug**
When I try to run Atlas and Iris in my server, the server starts to lag very quickly and I can't do any action

**Version Information**
- Iris Anticheat Version: 1.5.5
- Atlas Version: 1.0.7.1
- Bukkit/Spigot Version: 1.8.8

**Server Logs**
https://pastebin.com/ave2aQ2K

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I put Altas and Iris in my server file directory and started the server
2) I also tried to start in a clean server, without any plugin
3) .....

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.

**Additional context**

**Comment by funkemunky** [comment]
Hello, can you please provide the following information:

- How many players were online at the time.
- Do you have any screenshots with the /iris lag command. Iris has its own timings system.
- Do you use a host with the MultiCraft server software (a Minecraft specific host?).
- What version of Spigot were you using?
- Is this any better with the latest update?

**Comment by R3XET** [comment]
Hello, thanks for answering my question,
There were 0 players online in the network (just me)
I don't have screenshot because the lag was intensive and I can't do /iris
lag command
I'm using 1.8.8 spigot (only spigot, not paperspigot or other distributions)
With the last update I can finally use Iris, I have found some issues about
checks, but I know are going to be fixed.
Killaura Type G false flags when go up and down with the mouse, when you
hit a player; Also Fly Type B, I can't do parkour because of false flag;
Add a check for Step because I can jump over 4 blocks high without getting
flagged; Add a Jesus check and update NoSlowdown Check because I can easily
bypass with shit clients like Jigsaw. All checks were tested on my server
and your test server. In total the anticheat is very good and I hope you
will continue to update. Sorry for my English

Il giorno sab 2 feb 2019 alle ore 01:40 Dawson <notifications@github.com>
ha scritto:

**Comment by funkemunky** [comment]
This has been fixed in the 1.6.2 update of Iris. Thanks for the report!
