### ISSUE TITLE
Iris isn't compatible with Reflex Anticheat

### ISSUE THREAD

**Issue by Hyronymos1337** [funkemunky/Iris-Issues#30]
Latest Iris and Atlast
Paperspigot 1.8.8

**Comment by True-cc** [comment]
Why would you want iris and reflex?

**Comment by Hyronymos1337** [comment]
because reflex killaura check is 100x better as the iris killaura check

**Comment by True-cc** [comment]
I see

**Comment by funkemunky** [comment]
Reflex's killaura checks are not as good as Iris's. While Reflex may "detect" more, they false and its bot system is incredibly heavy on server resources. Please use the appropriate format next time and then maybe we can do something.
