### ISSUE TITLE
Server still crashing / timing out

### ISSUE THREAD

**Issue by Vantrex** [funkemunky/Iris-Issues#31]
**Describe the bug**
Server is timing/lagging out.

**Version Information**
- Iris Version: latest
- Atlas Version: latest
- Spigot 1.8.8 (custom, but we did not modify the packet system)

**Server Logs**
No Errors in the Console, the server is just timing out and restarting after 5-15 minutes.

**How to re-create**
idk tbh haha

**Screenshots/Video**
My other bug report on this issue (with crash report: https://github.com/funkemunky/Iris-Issues/issues/24 )

**Additional context**
My players a telling me that the server is crashing every 5 minutes, then they can´t join for like 15 minutes and then they can join again. It´s only crashing if there are 4+ players on (thats not that much^^)

**Comment by funkemunky** [comment]
Is this doing it without the anticheat? I would attempt to investigate this in your spigot first. There could always be compiling issues with spigots, I've experienced it myself.

**Comment by funkemunky** [comment]
Any results with the latest update?

**Comment by Vantrex** [comment]
Testing it later, will open a new issue if it is still a thing.
