### ISSUE TITLE
Errors and false flags

### ISSUE THREAD

**Issue by UniBoy666** [funkemunky/Iris-Issues#32]
**Describe the bug**
IT FALSE FLAGS PLS Funke ur a great developer and i hope you know how to fix it. Good luck
**Version Information**
- Iris Anticheat Version 1.5.5
- Atlas Version Latest
- Bukkit/Spigot Version This server is running NoksioSpigot (MC 1.7-1.8) (Implementing API version Papier-Robinet 1.7.X-1.8.X)

**Server Logs**
Provide the server log of the time the bug occurred.
https://hastebin.com/okoxefeqaf.apache
**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I jumped
2) I ran
3) idk :/

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.
http://prntscr.com/mfdstd
**Additional context**
I use BLC (Badlion Client) and it still false flags

**Comment by funkemunky** [comment]
The majority of these reported bugs have been fixed in the 1.6.2 update of Iris. However, the problems that are not fixed already have open GitHub Issue. 

It helps me work faster when I have the bugs you reported but with more detail that have been put in the open Issues.
