### ISSUE TITLE
NoFall, Fly (Type A) and Fly (Type B) False Flags

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#33]
**Describe the bug**
This issue happened when I walk on the snow.

**Version Information**
- Iris Anticheat Version: The 
- Atlas Version: Test 
- Bukkit/Spigot Version: Server

**Server Logs**
I don't have the logs because that server is not mine

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I walk on the snow.

**Screenshots/Video**
https://www.youtube.com/watch?v=HDjfhsbal10&feature=youtu.be

**Additional context**
No.

**Comment by funkemunky** [comment]
Thanks for the report. This has been fixed in the 1.6.2 and 1.6.1 update of Iris.
