### ISSUE TITLE
Bad Packets FP

### ISSUE THREAD

**Issue by wulfwuud** [funkemunky/Iris-Issues#35]
**Describe the bug**
BadPackets B FP

**Version Information**
- 1.5.6
- 1.0.8
- 1.12.2

**Server Logs**
nuffin

**How to re-create**
Use boat and dont move

**Screenshots/Video**
https://www.youtube.com/watch?v=L6t7DyXK5U4
https://i.imgur.com/2k4Un2w.png

**Additional context**
Do not turn on sound on video please

**Comment by funkemunky** [comment]
Thanks for the report, this has been fixed in release.
