### ISSUE TITLE
Atlas errors on shutdown

### ISSUE THREAD

**Issue by wulfwuud** [funkemunky/Iris-Issues#37]
**Describe the bug**
Atlas errors on shutdown

**Version Information**
- 1.5.6
- 1.0.8
- 1.12.2

**Server Logs**
https://pastebin.com/C2QdmY27

**How to re-create**
/stop

**Screenshots/Video**
nuffin here

**Additional context**
nuffin here

**Comment by funkemunky** [comment]
Fixed in release, thanks for the report.
