### ISSUE TITLE
Scaffold Bypass

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#38]
**Describe the bug**
I found the scaffold bypass.
Sometimes I got flags, but I can use it.

**Version Information**
- Iris Anticheat Version: Your Official
- Atlas Version: Official
- Bukkit/Spigot Version: Test Server

**Server Logs**
None

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Turn on the scaffold.

**Screenshots/Video**
https://www.youtube.com/watch?v=_lCDI_69iE0&feature=youtu.be

**Additional context**
None

**Comment by funkemunky** [comment]
I am taking note of this and working on a stable Scaffold check.

Also, this anticheat is not designed to **block** cheats. It's designed to detect and remove cheaters **accurately**.

**Comment by PiiSaba** [comment]
It means you don't have a plan to patch the bypass?

**Comment by funkemunky** [comment]
Of course.
