### ISSUE TITLE
Speed (Type B) and Timer (Type A) False FlagsBug Report

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#39]
**Describe the bug**
When I walk on the ice the the false flags happened.

**Version Information**
- Iris Anticheat Version: Your
- Atlas Version: Official
- Bukkit/Spigot Version: Test Server

**Server Logs**
I can't get them because the server is not mine.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Press Space Bar Quickly On Ice.

**Screenshots/Video**
https://www.youtube.com/watch?v=5hvv6lJG_6A&feature=youtu.be

**Additional context**
No.

**Comment by funkemunky** [comment]
I believe I have discovered the bug and made a fix. I will get to testing when I am home and let you know.

**Comment by PiiSaba** [comment]
I tested it on your official test server.
Speed (Type B) was not fixed.
I got Speed (Type C) false flag too.

**Comment by PiiSaba** [comment]
I will make a video to provide it tmr.

**Comment by funkemunky** [comment]
Is this fixed in the latest update?

**Comment by funkemunky** [comment]
This has been fixed.
