### ISSUE TITLE
Iris error on join while startup

### ISSUE THREAD

**Issue by wulfwuud** [funkemunky/Iris-Issues#40]
**Describe the bug**
Iris error on join while startup

**Version Information**
- 1.5.6
- 1.0.8
- 1.12.2

**Server Logs**
https://pastebin.com/jfiwQUSD

**How to re-create**
Try join server with iris while it is not fully started

**Screenshots/Video**
nuffin here

**Additional context**
nuffin here

**Comment by funkemunky** [comment]
Thanks for the report, this is fixed for the next update.
