### ISSUE TITLE
Server is still crashing / timing out

### ISSUE THREAD

**Issue by Vantrex** [funkemunky/Iris-Issues#41]
**Describe the bug**
Server is timing/lagging out, if 3+ players are online
**Version Information**
- Iris Anticheat Version
- Atlas Version
- Spigot 1.8.8 (custom, but we did not modify the packet system)

**Server Logs**
Again no error in the console.

**How to re-create**
idk you can message me on discord if you want to see it live (Vantrex#0753)

**Screenshots/Video**
Other report: https://github.com/funkemunky/Iris-Issues/issues/31 & https://github.com/funkemunky/Iris-Issues/issues/24
**Additional context**
The Server is crashing instantly after the third or fourth player did join

**Comment by funkemunky** [comment]
I'm going to have to investigate this issue with you further. Thanks for the help, I'll message you in discord.

**Comment by funkemunky** [comment]
I have confirmed this bug, and I'm on the hunt for the cause of it. Thanks for the report. I'll let you know when I make a confirmed fix.

**Comment by funkemunky** [comment]
I have made a confirmed fix, thanks for the report.
