### ISSUE TITLE
Bad packets flags

### ISSUE THREAD

**Issue by CruelWinter2** [funkemunky/Iris-Issues#43]
Describe the bug

When riding animals, you get flagged for bad packets. When teleporting, you get flagged for timer.

Version Information

Iris Anticheat Version: Latest
Atlas Version: Latest
Spigot version: 1.13.2

How to re-create

Bad packets
* Ride any rideable animal

Timer
* Teleport to another world. I used multiverse.

**Comment by CruelWinter2** [comment]
I found the problem. When I modify a check in the GUI, it resets to default settings. I am testing my server for bugs. The server is restarting constantly.

**Comment by CruelWinter2** [comment]
No. I did not see the button. I am still flagged for teleporting and riding animals. Also, I am flagged for killaura when building in creative or survival overtime.

**Comment by funkemunky** [comment]
Please report that then in a separate issue but providing as much information as possible please. This includes what checks are causing it, the server version, etc. Thank you.
