### ISSUE TITLE
Fly Type B/C ff 

### ISSUE THREAD

**Issue by Vantrex** [funkemunky/Iris-Issues#45]
**Describe the bug**
Fly B/C falseflag & Command error (i did not reload the server)
**Version Information**
- Latest
- Latest
- paperspigot 1.8.8

**Server Logs**
command error: (/atlas: https://pastebin.com/3FniSrEE /iris 2: https://pastebin.com/MChA5cC0 [I did not reload the server]

**How to re-create**
Just watch the video (fly ff)

**Screenshots/Video**
https://youtu.be/wo7mjet10As

**Comment by funkemunky** [comment]
Fixed in released update.
