### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MineFriend** [funkemunky/Iris-Issues#46]
iris version 1.6.1

atlas version 1.0.9

error: https://pastebin.com/9F5k81Qf

**Comment by MineFriend** [comment]
another error: https://pastebin.com/KbSyvH8P

**Comment by MineFriend** [comment]
same error??: https://pastebin.com/N2nwCs6v
please fix that iris does not execute the commands (maybe the cause that does not execute the commands is this error)

**Comment by funkemunky** [comment]
Fixed in the 1.6.2 update. Thanks for the report
