### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by True-cc** [funkemunky/Iris-Issues#5]
**Describe the bug**

**Version Information**
- Iris Anticheat Version : What ever the one on the test server is
- Atlas Version : What ever the one on the test server is
- Bukkit/Spigot Version : What ever the one on the test server is

**Server Logs**
Provide the server log of the time the bug occurred.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I uhm enabled hacks? I guess in video you can see.

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.
https://youtu.be/8fvBhxvm-kw

**Additional context**

I checked all the flies, they dont work.

**Comment by funkemunky** [comment]
Yes, we are going to be adding more checks for these cheats. Right now, we are primarily just focusing on getting things stable and compatible with 1.7.10-1.13.2. I will be working on a simple fast ladder check in the meantime, of course. Thank you for the report.

**Comment by funkemunky** [comment]
This has been fixed for the next update, thank you.
