### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by WindowsEight** [funkemunky/Iris-Issues#50]
**Describe the bug**
When using Speed I don't flag I just get the error.

I'm assuming it has something to do with the Spigot

**Version Information**
- Iris Anticheat Version 1.6.4
- Atlas Version 1.1.1
- aSpigot version 1.7.10-R1.1

**Server Logs**
https://hastebin.com/yalaxiduxo.md
I didn't see this the first time but here's the startup error http://prntscr.com/mi0qwk
Also an Atlas error http://prntscr.com/mi0reb

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Just use Speed

**Screenshots/Video**
None

**Additional context**
None

**Comment by funkemunky** [comment]
Yes, aSpigot is known to be incompatible. If you want my advice, don’t buy and use spigots made by skids.
