### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by MoCaveman** [funkemunky/Iris-Issues#55]
Spigot Name: MoCaveMan

Purchased Iris today and would like role on discord in pursuit of my license for the software.  
currently the verify bot is not working and I was instructed to "create a ticket".  

Thanks. 
WCSleeper AKA MoCaveman
WCSleeper@GMail.cim

**Comment by FozzieHi** [comment]
Do you still not have a license?

**Comment by MoCaveman** [comment]
I had to give up on Iris after funkemunky did.  I was successful at getting
a refund from paypal and have moved on to anther vendor.  Thank you for
your efforts.

W.C. Sleeper
