### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by PingDevs** [funkemunky/Iris-Issues#56]
**Describe the bug**
The bug is when you throw enderpearls it starts flagging

**Version Information** Latest
- Iris Anticheat Version Latest
- Atlas Version 1.1.1
- Bukkit/Spigot Version 1.8.8

**Server Logs**
Provide the server log of the time the bug occurred.
N/A 

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I threw enderpearls
2) 
3) .....

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.

**Additional context**

**Comment by FozzieHi** [comment]
Please try this with the latest version of [Iris](https://www.spigotmc.org/resources/iris-anticheat-advanced-cheat-detection-1-7-1-13.53721/)
