### ISSUE TITLE
WARN messages in Console 

### ISSUE THREAD

**Issue by MoCaveman** [funkemunky/Iris-Issues#59]
Seem to be bleeding Red WARN msg's on console.  Installed latest today on my 1.13.2 server.   Did I miss a checkbox?  THanks.   Here is the console messages.  https://pastebin.com/PEvPrDnP

**Version Information**
- Iris Anticheat Version  : 1.7-1.13 
- [Atlas] Loading Atlas v1.1.3.1
- Bukkit/Spigot Version 1.13.2

**Server Logs**
Provide the server log of the time the bug occurred.
https://pastebin.com/PEvPrDnP

**How to re-create**
I installed on test platform and when my player logged in I received a large amount of WARN messages on console as if DEBUG was running.  

**Additional context**

**Comment by funkemunky** [comment]
Give the proper version of Atlas used please.

**Comment by MoCaveman** [comment]
> Give the proper version of Atlas used please.

sorry, updated ticket from console on Atlas version.  Thanks.

**Comment by MoCaveman** [comment]
Funk will you be offering support on these projects going forward?

**Comment by FozzieHi** [comment]
@MoCaveman You'll need to install [Atlas version 1.1.3.1](https://github.com/funkemunky/Atlas/releases/tag/1.1.3.1) for now. When I release a new update the latest Atlas version will be supported.

**Comment by FozzieHi** [comment]
@MoCaveman A new update for Iris has been released, this supports the latest Atlas version.
