### ISSUE TITLE
Error with aSpigot

### ISSUE THREAD

**Issue by WindowsEight** [funkemunky/Iris-Issues#60]
**Describe the bug**

**Version Information**
- Iris Anticheat Version - 1.6.4
- Atlas Version - 1.1.3.1
- Bukkit/Spigot Version - aSpigot 1.7.10-R1.1

**Server Logs**
https://pastebin.com/vWJRDeXv

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Using /iris does nothing just makes errors

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.

**Additional context**

**Comment by FozzieHi** [comment]
aSpigot is known to be incompatible with Iris, you're going to have to use regular Spigot or a fork that is compatible.
