### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by JasperWorld** [funkemunky/Iris-Issues#63]
**Describe the bug**
NoSlowdown check not working, (flagging BadPackets D when standing still, and not flagging anything while moving)

**Version Information**
- Iris Anticheat Version: https://pastebin.com/YxhnFcf7
- Atlas Version: https://pastebin.com/YxhnFcf7
- Bukkit/Spigot Version: https://pastebin.com/YxhnFcf7

ViaV. installed: Yes

**Server Logs**
https://pastebin.com/YxhnFcf7

**Screenshots/Video**
Video: https://youtu.be/Nh0pVV3_tEs

**Comment by FozzieHi** [comment]
This is normal behaviour, some clients use packets instead of the Vanilla NoSlowdown so Type D will flag if you have NoSlowdown enabled.

**Comment by funkemunky** [comment]
How clients bypass NoCheatPlus with NoSlowdown is by spamming right click 20 times per second so NoCheatPlus thinks you arent blocking when you are. 

To ensure that false reports like this don't happen again, try to turn off every cheat so no one is confused.

**Comment by funkemunky** [comment]
I suggest that
