### ISSUE TITLE
Spamming Console and can not move with out failing a check

### ISSUE THREAD

**Issue by Gnoarn** [funkemunky/Iris-Issues#64]
**Describe the bug**
Setup the plugin going into the games server i am about to launch 
and can not move with out failing checks for movement or flight.
which i dont have a plugin in for flight.

**Version Information**
- Iris Anticheat Version
1.7.3
- Atlas Version
1.1.3.4
- Bukkit/Spigot Version
git-Paper-476 (MC: 1.13.2)
**Are you using the ViaVersion plugin?**
no backward compatability on this server
**Server Logs**
way to long for a paste bin. but have a partial
https://pastebin.com/qiHBybGw
Provide the server log of the time the bug occurred.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I did this. spawned in. tried to fly forgetting i dont have essentials installed got kicked for movement A
2) I did that. spawned back in ran around and got kicked again for same movement.
3) disabled said movement in the configs. did iris reload. got a chunk load of error logs.
rebooted
and still get kicked for the same movement.
was hoping to find a fast solution to work since sky,egg, and bed wars launch the 17th.
for my network.

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.

**Additional context**

**Comment by Gnoarn** [comment]
here is my list of plugins on this particular server
 Plugins (41): AddLight, Atlas, BuycraftX, Citizens, CommandNPC, DeluxeChat, DeluxeMenus, DeluxeTags, DiscordSRV, GAListener, HolographicDisplays, HolographicExtension, HolographicScoreboard, Libs4Paper, LiteBans, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI, OpenInv, PerWorldInventory, PlaceholderAPI, PlugMan, ProBedwars, ProEggwars, ProSkyWars, ProtocolLib, SignEdit, SignEditor, SimpleAPI, SimpleGlow, SimplePets, spark, SuperVanish, Tab, Vault, Votifier, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, Iris

**Comment by FozzieHi** [comment]
Try deleting your config file and use `/iris menu` to disable / enable checks. If you believe the movement bug is an error on Iris's detection and not due to your plugins enhancing movement speed etc, then please say so.

**Comment by FozzieHi** [comment]
There is an ongoing issue at the moment with Movement & Flight bugs in 1.13.2 I cannot replicate this myself on my own server with default Spigot, it may be a PaperSpigot issue unless I can track this down further I cannot fix the issue.

**Comment by Gnoarn** [comment]
i dont know if its a paper thing or bungee thing. had a bunch of badpacket as well

**Comment by Gnoarn** [comment]
reach autoclicker when simple mining. is there anything that actually works in this plugin. i have tried adding higher limitations and still nothing. and the ui all it does is set stuff back to fail setting that constantly kick people for no good reason. and the log file is a mile long. even with flight and speed disabled.

**Comment by FozzieHi** [comment]
Did you click the save button on the UI? Anyway, I'm trying to fix this issue now.

**Comment by FozzieHi** [comment]
@Gnoarn this seems to be an issue with PaperSpigot 1.13.2 renaming methods, you can either try and update PaperSpigot or install Spigot 1.13.2
