### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by JoeProKill2000** [funkemunky/Iris-Issues#65]
**Describe the bug**
If I am in gms or gmc, and I type /fly, fly up, and type /fly in the air, it will tp me to the ground and spam hack reports.

**Version Information**
- Iris Anticheat Latest
- Atlas Latest
- Bukkit/Spigot git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Are you using the ViaVersion plugin?**
Yes

**Server Logs**
Provide the server log of the time the bug occurred.
The log is just me typing /fly twice pretty much. The anticheat isn't being logged.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I typed /fly (WITH ESSENTIALS)
2) I flew up 10 blocks
3) I typed /fly
4)I got tped down with iris saying I was hacking

**Screenshots/Video**
https://www.mediafire.com/file/4nnp4idwp215k6b/Minecraft_1.12.2_3_16_2019_11_06_37_AM.mp4/file

**Additional context**
Not really.

**Comment by FozzieHi** [comment]
I'll be working on this for the next update.

**Comment by JoeProKill2000** [comment]
Ok

**Comment by FozzieHi** [comment]
This is fixed in the next update, when it releases be sure to check yourself, if it's not fixed then please open a new ticket.

**Comment by JoeProKill2000** [comment]
Alright
