### ISSUE TITLE
False flags

### ISSUE THREAD

**Issue by CruelWinter2** [funkemunky/Iris-Issues#66]
When in combat with entities like pigs, I get flagged for reach. When falling, I get flagged for nofall.

My server is running
PaperSpigot 1.8.8
ViaVersion
Yesterday’s update for Iris
Atlas 1.1.3.4

**Comment by FozzieHi** [comment]
Please fill out the required format using copy & paste and show a video.

**Comment by CruelWinter2** [comment]
I don’t have screen recording software.

**Comment by FozzieHi** [comment]
Can you DM me your server IP on Discord? Fozzie#0001
