### ISSUE TITLE
False Speed A/B

### ISSUE THREAD

**Issue by JoeProKill2000** [funkemunky/Iris-Issues#67]
**Describe the bug**
If you are holding a sword with the NBT tag of SPEED increased, it will count you as speed hacking. Since you have no potion effects but your holding the sword, it still thinks your hacking.

**Version Information**
- Iris Anticheat 1.7.6
- Atlas 1.1.3.4 (Iris does not work with 1.1.3.5)
- Bukkit/Spigot git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Are you using the ViaVersion plugin?** Yes

**Server Logs**
No logs. I have anticheat set to not record logs. You can see chat in video.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I gave myself a sword with NBT Tag of +0.05 speed
2) I held it in my hand.
3) I sprinted.

**Screenshots/Video**
https://www.mediafire.com/file/qg7krawr4g0r8d8/Minecraft_1.12.2_3_17_2019_3_33_39_PM.mp4/file

**Additional context**
Might be hard to fix due to the speed being given by an item but please fix it.

**Comment by FozzieHi** [comment]
Can you give me a full list of your plugins?

**Comment by JoeProKill2000** [comment]
Plugins (127): PlayerSimulator, JoinCommands, Vehicles, PlugMan, StackSpawner, VillageGenerator, HandFixer, CustomRecipes, OreGenerator, NoVPN, ReferralCodes, StripArmor, AdvancedBan, VehiclesFlags, VoidSpawn, ProtocolLib, Multiverse-Core, MassSayReborn, InventoryRollback, VotingPlugin, FastAsyncWorldEdit, Vouchers, PocketGames, PermissionsEx, iConomy, AntiCropTrample, mcMMO, Helix, Multiverse-Portals, ServerListPlus, ServerRestorer, ProtocolSupport, PluginConstructorAPI, Glow, PlaceholderAPI, Lands, PlayTime, AnimatedInventory, AutoFly, UserInterfaceAPI, Lockette, Atlas, OldCombatMechanics, NoFall, AntiAutoClicker, PlayerReport, TagsGUI, IPLogger, ParticleLIB, CoreProtect, BetterGoldenApples, WorldEdit, bSpace, OpenInv, ClearLag, IllegalStack, WorldBorder, BuycraftX, Votifier, AntiSplit, NightVision, LibsDisguises, NoAI, PunishGUI, Twerking-Crops, MOTDgdCommandAd, EffectLib, Laser, CS-CoreLib, Vault, PlayerDeathLocation, iControlU, GUIMaker, Iris, EpicRename, MoneyPouch, HolographicDisplays, ChatItem, PlayerVaults, Tablist, MyCommand, afkTerminator, AgarthaLib, Banknotes, CommandSigns, Citizens, CrazyAuctions, DeathChest, TokenManager, ChatGames, CrazyCrates, WorldGuard, ProdigyGadget, Slimefun, MoreFish, EditableSign, Essentials, ExtraGear, SafeTrade, Magic, Parkour, XPBoost, SuperVanish, CombatTagPlus, MythicMobs, Quests, EssentialsGeoIP, CommandNPC, TitleManager, CompatNoCheatPlus, CoinFlipper, SilkSpawners, MagicWorlds, Shopkeepers, EssentialsChat, ChestShop, MyItems, EssentialsXMPP, EssentialsProtect, ChatManager, EssentialsSpawn, WorldGuardExtraFlags, StackMob, ShopGUIPlus, CrazyEnchantments, LeaderHeads, HeadHunter

**Comment by FozzieHi** [comment]
Iris doesn't officially support Custom Enchant plugins, they can be added using our API by the developer, this generally causes a lot of false positives anyway.

**Comment by JoeProKill2000** [comment]
It’s not the custom enchants. I gave it an NBT tag of speed, which comes default into vanilla Minecraft. There was not a single custom enchant. Thanks.

**Comment by FozzieHi** [comment]
I am aware, I thought I sent a message saying it was fixed in the next update - well it is. I was just saying you may encounter some more false positives in the future with CustomEnchants.

**Comment by JoeProKill2000** [comment]
Thank you. I messaged the developer of the plugin to ask for integration

**Comment by JoeProKill2000** [comment]
Censoring my plugins to keep them private.
