### ISSUE TITLE
Jump Boost False Positive

### ISSUE THREAD

**Issue by JoeProKill2000** [funkemunky/Iris-Issues#68]
**Describe the bug**
I gave myself Jump Boost 4, and turned off my fly. When I jumped, it made me stuff in air and counted it as hacks.

**Version Information**
- Iris Anticheat 1.7.6
- Atlas Version 1.1.3.4
- Bukkit/Spigot Version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Are you using the ViaVersion plugin?**
Yes

**Server Logs**
Provide the server log of the time the bug occurred.
My anticheat doesn't log detections

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I gave myself Jump Boost 4
2) I sprinted and jumped
3) I got counted for hacks

**Screenshots/Video**
https://www.mediafire.com/file/yfty7ax5uj3nox7/Minecraft_1.12.2_3_18_2019_5_09_33_PM.mp4/file

**Additional context**
Nothing

**Comment by FozzieHi** [comment]
This is fixed in the next update, thanks for reporting it.
