### ISSUE TITLE
Reach Type C False

### ISSUE THREAD

**Issue by JoeProKill2000** [funkemunky/Iris-Issues#69]
**Describe the bug**
For some reason, when my player hits me, and im in creative mode, they get counted for reach. Flying or on ground.

**Version Information**
- Iris Anticheat 1.7.6
- Atlas 1.1.3.4
- Bukkit/Spigot git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Are you using the ViaVersion plugin?**
yes

**Server Logs**
Anticheat doesn't log detections

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I went in gmc on main
2) I hit my main on an alt
3) My alt was classified for reach

**Screenshots/Video**
Detection in chat - https://prnt.sc/mzp7ra
Videos both on ground and in air - https://www.mediafire.com/file/bf68z7pcs12cc1c/Reach.rar/file

**Additional context**
Works flying or on ground

**Comment by JoeProKill2000** [comment]
It’s not a plugin. He had nothing on him.

**Comment by FozzieHi** [comment]
@JoeProKill2000 still, some plugins may have conflicts with Iris. I cannot reproduce this on my server.

**Comment by JoeProKill2000** [comment]
Plugins (137): PlayerSimulator, JoinCommands, Vehicles, PlugMan, StackSpawner, VillageGenerator, HandFixer, CustomRecipes, OreGenerator, NoVPN, ReferralCodes, StripArmor, AdvancedBan, VehiclesFlags, VoidSpawn, ProtocolLib, Multiverse-Core, MassSayReborn, InventoryRollback, VotingPlugin, FastAsyncWorldEdit, Vouchers, PocketGames, PermissionsEx, iConomy, AntiCropTrample, mcMMO, Helix, Multiverse-Portals, ServerListPlus, ServerRestorer, ProtocolSupport, PluginConstructorAPI, Glow, PlaceholderAPI, Lands, PlayTime, AnimatedInventory, AutoFly, UserInterfaceAPI, Lockette, Atlas, OldCombatMechanics, NoFall, AntiAutoClicker, PlayerReport, TagsGUI, IPLogger, ParticleLIB, LightAPI, CoreProtect, BetterGoldenApples, WorldEdit, bSpace, OpenInv, ClearLag, CrackShot, IllegalStack, WorldBorder, BuycraftX, Votifier, AntiSplit, NightVision, LibsDisguises, CrackShotPlus, NoAI, PunishGUI, Twerking-Crops, MOTDgdCommandAd, EffectLib, Laser, CS-CoreLib, Vault, PlayerDeathLocation, iControlU, GUIMaker, Iris, EpicRename, MoneyPouch, HolographicDisplays, ChatItem, PlayerVaults, Tablist, MyCommand, afkTerminator, AgarthaLib, Banknotes, CommandSigns, CrackShotAdditions, Citizens, Sentinel, CrazyAuctions, DeathChest, NPC_Destinations, TokenManager, ChatGames, CrazyCrates, NPC_Police, WorldGuard, ProdigyGadget, Slimefun, UltimateDrugs, MoreFish, EditableSign, Essentials, ExtraGear, SafeTrade, Magic, Parkour, XPBoost, SuperVanish, CombatTagPlus, MythicMobs, Quests, EssentialsGeoIP, CommandNPC, TitleManager, CompatNoCheatPlus, NPCDestinations_Animator, CoinFlipper, SilkSpawners, MagicWorlds, Shopkeepers, NPCDestinations_Farmer, EssentialsChat, ChestShop, MyItems, EssentialsXMPP, EssentialsProtect, ChatManager, EssentialsSpawn, WorldGuardExtraFlags, StackMob, ShopGUIPlus, CrazyEnchantments, LeaderHeads, HeadHunter

You have seen my plugins before. None of them conflict with Iris.

**Comment by FozzieHi** [comment]
I still cannot reproduce this myself.

**Comment by JoeProKill2000** [comment]
I use the default config. Only thing changed is not to punish players other than kick.

**Comment by JoeProKill2000** [comment]
Weird, it seems to stop but act up again every once in a while. If it becomes a major issue, I will contact you. For now, I'm closing this issue. Thanks for the support :)
