### ISSUE TITLE
Reach C With Guns

### ISSUE THREAD

**Issue by JoeProKill2000** [funkemunky/Iris-Issues#70]
**Describe the bug**
Using crackshot, when I shot a mob, then hit the mob, it said I was using reach.  I don't know how, but it happened in creative and survival.

**Version Information**
Iris Anticheat 1.7.6
Atlas 1.1.3.4
Bukkit/Spigot git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Are you using the ViaVersion plugin?**
Yes

**Server Logs**
Anticheat doesn't log

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I shot mobs
2) I was detected for reach
3) I hit the mobs with the gun
4) I was detected for reach

**Screenshots/Video**
https://www.mediafire.com/file/sw0ppfxtqd98oxt/Minecraft_1.12.2_3_19_2019_9_44_49_PM.mp4/file

**Additional context**
I am using CrackShot.

**Comment by FozzieHi** [comment]
Iris doesn't support guns, I'd suggest disabling the check.

**Comment by JoeProKill2000** [comment]
But then players could use reach type c. Could you add support?

**Comment by FozzieHi** [comment]
There are 3 checks for reach, the other two would still detect Reach.

**Comment by JoeProKill2000** [comment]
Yes but type C seems to be most used. Any way you could add support?

**Comment by FozzieHi** [comment]
> Yes but type C seems to be most used. Any way you could add support?

If CrackShot has an actual API for me to use then I could possibly add support.

**Comment by JoeProKill2000** [comment]
I'll contact Crackshot. :)
