### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by HappyTNTguy** [funkemunky/Iris-Issues#71]
**Describe the bug**

**Version Information**
- Iris Anticheat Version: Latest
- Atlas Version: 1.1.3.5
- Bukkit/Spigot Version: ExoSpigot 1.7.10

**Are you using the ViaVersion plugin?** None

**Server Logs**
Provide the server log of the time the bug occurred.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) https://streamable.com/agf2k

**Screenshots/Video**
https://streamable.com/agf2k

**Additional context**
I'm using exospigot 1.7.10.

**Comment by FozzieHi** [comment]
That doesn't tell me how to reproduce, what did you do before this?

**Comment by HappyTNTguy** [comment]
I just joined and started moving around.

**Comment by WindowsEight** [comment]
I have experienced this bug as well, all you do is move and it flags from what I've seen, you don't have to do anything special

**Comment by HappyTNTguy** [comment]
I'd like to know if this is getting fixed in the next update.

**Comment by FozzieHi** [comment]
I still cannot reproduce this, does this happen constantly when moving or only sometimes? @HappyTNTguy @WindowsEight

**Comment by HappyTNTguy** [comment]
for me it happens constantly.
I can send the spigot jar if needed

**Comment by HappyTNTguy** [comment]
Just tried the newest version and seemed to be fixed
