### ISSUE TITLE
Iris Bug Report

### ISSUE THREAD

**Issue by WindowsEight** [funkemunky/Iris-Issues#72]
**Describe the bug**
I hit another player and I flag reach and the other player flags velocity

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Are you using the ViaVersion plugin?**
No

**Server Logs**
None

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Login
2) Attack another player

**Screenshots/Video**
https://www.youtube.com/watch?v=hJGyn3-_jdA&feature=youtu.be

**Additional context**
Plugin list if it helps: http://prntscr.com/n3a84d

**Comment by FozzieHi** [comment]
This should be fixed in the next update, thanks for reporting it.
