### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by WindowsEight** [funkemunky/Iris-Issues#74]
**Describe the bug**
Jumping into the void sometimes causes false flags with the "Nofall" and "Fly (Type B)" checks. (0:12 seconds in the video below)

Attacking a player through to stairs which are facing each other causes false flags with the "KillAura (Type G)" and "BadPackets (Type D)" check. (0:25 seconds in the video below)

Attacking a player through a slab placed on top of a block with a block above it causes false flags with the "BadPackets (Type D)" and "Reach (Type C)" check. (1:00 in the video below)

Spamming spacebar in a 2 high building causes "GroundSpoof" to false flag (1:25 in the video below)

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: aSpigot version 1.7.10-R1.1 (Implementing API 1.8.x)

**Are you using the ViaVersion plugin?**
No

**Server Logs**
No errors or logs

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Video below shows how to do it

**Screenshots/Video**
This video shows all of the bugs (https://www.youtube.com/watch?v=_mSNC_mbiRU&feature=youtu.be)

**Additional context**

**Comment by FozzieHi** [comment]
The NoFall & Fly Type B falses should be fixed in the latest update, although I cannot replicate the other issues, I'll have to look more into it.
