### ISSUE TITLE
Reach Type A false flag

### ISSUE THREAD

**Issue by WindowsEight** [funkemunky/Iris-Issues#75]
**Describe the bug**
The Reach (Type A) check false flags if you hit someone while in gamemode c

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: aSpigot version 1.7.10-R1.1 (Implementing API 1.8.x)

**Are you using the ViaVersion plugin?**
No

**Server Logs**
No errors or logs

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Enter gamemode c
2) Attack a player from as far away as possible

**Screenshots/Video**
https://www.youtube.com/watch?v=PNJrq4ao_pE&feature=youtu.be

**Additional context**

**Comment by FozzieHi** [comment]
This is fixed in the next update! thanks for reporting it.
