### ISSUE TITLE
HitBox false flag

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#76]
**Describe the bug**
HitBox check false flag if I hit a player. 

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: 1.8.8

**Are you using the ViaVersion plugin?**
No

**Server Logs**
Logs in the video.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
↓ Please watch the video below.

**Screenshots/Video**
https://www.youtube.com/watch?v=MoVsIM69e3M&feature=youtu.be

**Additional context**

**Comment by FozzieHi** [comment]
Can you do `/iris bugreport info`, please.

**Comment by PiiSaba** [comment]
https://pastebin.com/UwE3MPK8
here you are

**Comment by FozzieHi** [comment]
I still cannot reproduce this, is it still a problem?
