### ISSUE TITLE
BadPackets (Type A) false flags.

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#77]
**Describe the bug**
Set the gamemode to creative then left the server and logging back, I got this false flags.

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: 1.8.8

**Are you using the ViaVersion plugin?**
No

**Server Logs**
The video shows.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Set your gamemode to creative
2) left the server
3) loging back to the server
4) move forward

**Screenshots/Video**
https://www.youtube.com/watch?v=yR_tuHQTfp4

**Additional context**

**Comment by FozzieHi** [comment]
I cannot replicate this, @funkemunky any idea?

**Comment by HappyTNTguy** [comment]
I have the same issue, when a player joins and starts flying, it will flag.

**Comment by funkemunky** [comment]
It’s likely a concurrency issue which I fixed in the latest update of Atlas.
