### ISSUE TITLE
Criticals false flags

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#78]
**Describe the bug**
When I hit a player in the water then I got this false flag.

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: 1.8.8

**Are you using the ViaVersion plugin?**
No

**Server Logs**
The video shows.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Hit a player in the water.

**Screenshots/Video**
https://www.youtube.com/watch?v=oGVIEIm7V7s&feature=youtu.be

**Additional context**

**Comment by FozzieHi** [comment]
Does this only occur in water?

**Comment by PiiSaba** [comment]
I think so.

**Comment by FozzieHi** [comment]
This should be fixed in the next update, thanks for the report.
