### ISSUE TITLE
GroundSpoof and Fly (Type B) false flags

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#79]
**Describe the bug**
When I spammed space key on the keyboard then this happened.

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: 1.8.8

**Are you using the ViaVersion plugin?**
No

**Server Logs**
The video shows.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Spam your space key.

**Screenshots/Video**
https://www.youtube.com/watch?v=Nox2gdwVVq8&feature=youtu.be

**Additional context**

**Comment by FozzieHi** [comment]
This is very weird, I thought I fixed this, can you record the video while using `/iris debug GroundSpoof`?

**Comment by PiiSaba** [comment]
okay.

**Comment by PiiSaba** [comment]
https://www.youtube.com/watch?v=Uw1FBozrpCA&feature=youtu.be

**Comment by FozzieHi** [comment]
This is fixed in the next update - thanks for reporting!
