### ISSUE TITLE
[Infrequently] Speed (Type A and B) false flags 

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#81]
**Describe the bug**
When I am bunny hopping on the ice, then this happened.
But these false flags are so rare.

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: 1.8.8

**Are you using the ViaVersion plugin?**
No

**Server Logs**
The video shows.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Hop on the ice.

**Screenshots/Video**
https://www.youtube.com/watch?v=6TP_Zgtjn_8&feature=youtu.be

**Additional context**

**Comment by FozzieHi** [comment]
Should be fixed in the latest update!
