### ISSUE TITLE
Speed (Type B) false flags.

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#82]
**Describe the bug**
Throw many ender pearls.

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: 1.8.8

**Are you using the ViaVersion plugin?**
No

**Server Logs**
The video shows.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I did this.
2) I did that.
3) .....

**Screenshots/Video**
https://www.youtube.com/watch?v=eqiqlVJH7hA&feature=youtu.be

**Additional context**

**Comment by FozzieHi** [comment]
This is fixed in the next update - thanks for reporting it.
