### ISSUE TITLE
FastBow false flags.

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#83]
**Describe the bug**
Right click ASAP.

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: 1.8.8

**Are you using the ViaVersion plugin?**
No

**Server Logs**
The video shows.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Right click ASAP.

**Screenshots/Video**
https://www.youtube.com/watch?v=2uK3g89U2a4&feature=youtu.be

**Additional context**

**Comment by FozzieHi** [comment]
What Spigot version are you using? screenshot `/ver` please. I can reproduce hardly any of these bugs.

**Comment by PiiSaba** [comment]
http://prntscr.com/n4y9fa

**Comment by FozzieHi** [comment]
This is fixed in the next update - thanks for reporting it.
