### ISSUE TITLE
Criticals and NoSlowdown false flags.

### ISSUE THREAD

**Issue by WindowsEight** [funkemunky/Iris-Issues#84]
**Describe the bug**
Noslowdown just flags while walking normally. (0:10 seconds in the video below)

Criticals randomly started flagging. (0:55 seconds in the video below)

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: aSpigot version 1.7.10-R1.1 (Implementing API 1.8.x)

**Are you using the ViaVersion plugin?**
No

**Server Logs**
None

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I just walked around and hit the other person

**Screenshots/Video**
https://www.youtube.com/watch?v=QEn3sudeiFQ&feature=youtu.be

**Additional context**

**Comment by FozzieHi** [comment]
Does this happen constantly? I believe this is an issue with 1.7.10, Iris doesn't officially support this version.

**Comment by WindowsEight** [comment]
No it's not very consistent

**Comment by FozzieHi** [comment]
Is this still present in 1.8.3? I cannot reproduce this.
