### ISSUE TITLE
Fly False Flag

### ISSUE THREAD

**Issue by coolpvpv** [funkemunky/Iris-Issues#85]
Version Information
Iris Anticheat Version 1.7.9
Atlas Version 1.1.3.5
Bukkit/Spigot Version 1.7.10

Are you using the ViaVersion plugin
No

How to re-create
Steps:
1) i got on a horse and got off 

Video: https://streamable.com/xtd5v

**Comment by FozzieHi** [comment]
Can you try and use the latest version of Iris? I cannot reproduce this.

**Comment by FozzieHi** [comment]
This is fixed in the next update - thanks for reporting it.
