### ISSUE TITLE
Fly (Type B) and NoFall, Speed (Type B) false flags

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#86]
**Describe the bug**
Shoot yourself with a bow with a punch 2 enchantment, then this happened.

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: 1.8.8

**Are you using the ViaVersion plugin?**
No

**Server Logs**
The video shows.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Attach the Punch 2 enchantment to the bow
2) Shoot yourself

**Screenshots/Video**
https://www.youtube.com/watch?v=e14pbDqWuT0&feature=youtu.be

**Additional context**
No

**Comment by FozzieHi** [comment]
Should be fixed in the latest update, please retry this.
