### ISSUE TITLE
Fly (Type B) false flags

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#87]
**Describe the bug**
When you try to move down using the ladder, press the shift key.

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: 1.8.8

**Are you using the ViaVersion plugin?**
No

**Server Logs**
The video shows.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Try to move down using ladder
2) Press the shift key

**Screenshots/Video**
https://www.youtube.com/watch?v=rFmt-z9Sl9Y&feature=youtu.be

**Additional context**
No

**Comment by FozzieHi** [comment]
Send your plugin list, please.

**Comment by PiiSaba** [comment]
http://prntscr.com/n52bab
There are only 3 plugins xd

**Comment by FozzieHi** [comment]
This is fixed in the next update - thanks for reporting it.
