### ISSUE TITLE
BadPackets (Type F)  false flags

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#88]
**Describe the bug**
Shoot a player with Punch 30 levels.

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: 1.8.8

**Are you using the ViaVersion plugin?**
No

**Server Logs**
The video shows.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Type the command: /give @p bow 1 0 {ench:[{id:49,lvl:30},{id:51,lvl:1}],Unbreakable:1}
2) Shoot a player

**Screenshots/Video**
https://www.youtube.com/watch?v=vjZzSxi9Lw4&feature=youtu.be

**Additional context**
No

**Comment by PiiSaba** [comment]
oops. This issue is able to happen by shooting yourself easily.

**Comment by FozzieHi** [comment]
I'm sorry but I don't think I'm ever gonna support Punch 30 - that's just unrealistic and would lower cheat detections significantly.

**Comment by PiiSaba** [comment]
um. I see but you should support.

**Comment by FozzieHi** [comment]
Why? what server would be using Punch 30 - this would just reduce the cheats I can detect.

**Comment by PiiSaba** [comment]
I see.
Bad Packets (Type F) occurs when the punch enchantment level is 8 or higher.
I've tested.

**Comment by FozzieHi** [comment]
I can probably patch lower levels, but I still find it unlikely for people to have punch 8.
