### ISSUE TITLE
Fly (Type E) false flags

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#89]
**Describe the bug**
I'm sorry but I can't describe the bug.
You should watch the video below. sorry.

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: 1.8.8

**Are you using the ViaVersion plugin?**
No

**Server Logs**
The video shows.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) The video shows. (I'm sorry)

**Screenshots/Video**
https://www.youtube.com/watch?v=oG4yZc7zTZ4&feature=youtu.be

**Additional context**
No

**Comment by FozzieHi** [comment]
Thanks for reporting! I've already patched this for Cobblestone Walls, I can just add Fences to that list.
