### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by True-cc** [funkemunky/Iris-Issues#9]
**Describe the bug**

**Version Information**
- Iris Anticheat Version : Test server version
- Atlas Version : Test server version
- Bukkit/Spigot Version : Test server version

**Server Logs**
Provide the server log of the time the bug occurred.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I enabled hacks.

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.
https://youtu.be/ouVkb7wR0js
**Additional context**

**Comment by funkemunky** [comment]
Thanks for the report.
