### ISSUE TITLE
FastPlace false flags

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#90]
**Describe the bug**
Occurs when doing Ninja Bridging.

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: 1.8.8

**Are you using the ViaVersion plugin?**
No

**Server Logs**
The video shows.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Do ninja bridging.

**Screenshots/Video**
https://www.youtube.com/watch?v=IvKBK1WFBFo&feature=youtu.be

**Additional context**
No

**Comment by FozzieHi** [comment]
This is fixed in the next update.
