### ISSUE TITLE
BadPackets (Type A) Flag when player joins

### ISSUE THREAD

**Issue by HappyTNTguy** [funkemunky/Iris-Issues#91]
**Describe the bug**

**Version Information**
- Iris Anticheat Version: Latest Version as of 3/30/2019 5:30 PM PST
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: ExoSpigot 1.7.10

**Are you using the ViaVersion plugin?**
No
**Server Logs**
Provide the server log of the time the bug occurred.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I join the server in CREATIVE mode
2) I started flying around
3) It flags and gets me stuck
4) It bans

**Screenshots/Video**
https://streamable.com/afr43

**Additional context**
Im using ExoSpigot 1.7.10

**Comment by FozzieHi** [comment]
1.7.10 is not supported, and I've never heard of ExoSpigot - but this issue is apparent in other versions and has been fixed. This may be the reason you're experiencing NoSlowdown issues as well, can you upgrade to 1.8?

**Comment by HappyTNTguy** [comment]
My HCF Core does not support a 1.8 spigot so I can't upgrade

**Comment by FozzieHi** [comment]
Then you'll have to disable NoSlowdown.
