### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Firulaisito** [funkemunky/Iris-Issues#92]
**Describe the bug**

**Version Information**
- Iris Anticheat Version
- Atlas Version
- Bukkit/Spigot Version

**Are you using the ViaVersion plugin?**

**Server Logs**
Provide the server log of the time the bug occurred.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Set own speed to 0.8 or less (I use It for an plugin of ffa)
2) Walk xD

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.
Here: https://www.youtube.com/watch?v=Z0Z3UEuzSBs

**Additional context**
Nop

**Comment by FozzieHi** [comment]
Actually fill out the form please.
