### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by CruelWinter2** [funkemunky/Iris-Issues#93]
**Describe the bug**
A clear and concise description of what the bug is. Speed false flag

**Version Information**
- Iris Anticheat Version: 1.8.2
- Atlas Version: 1.1.4.1
- Bukkit/Spigot Version: PaperSpigot 1.8.8

**Are you using the ViaVersion plugin?*Yes*

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) When sprinting and jumping, you are flagged for speed.

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.
https://drive.google.com/file/d/1G0wOOslm1BQPfc8RPKci9c3dXyl37KCx/view?usp=drivesdk

**Comment by KermanIsPretty** [comment]
PAPER SPIGOT EWWWWWWWWWWWWWWWWWWWWW

**Comment by FozzieHi** [comment]
PaperSpigot 1.8 has a bug in it, this may be related to this, please use regular Spigot.
