### ISSUE TITLE
Autoclicker Type A when mining

### ISSUE THREAD

**Issue by JoeProKill2000** [funkemunky/Iris-Issues#94]
**Describe the bug**
I was just mining with efficiency 5 fortune 3 pickaxe, and I was getting autoclicker type a alerts.

**Version Information**
- Iris Anticheat 1.8.2
- Atlas Version 1.1.4.1
- Bukkit/Spigot Version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Are you using the ViaVersion plugin?**
yes

**Server Logs**
no logs

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I mined
2) It created alerts

**Screenshots/Video**
https://www.mediafire.com/file/y3amoia97tyrvet/Minecraft_1.12.2_4_10_2019_6_16_29_PM.mp4/file

**Additional context**
This is a very important check as it usually is the detector or killaura so I need it working.

**Comment by FozzieHi** [comment]
This is fixed in the next update.
