### ISSUE TITLE
Autoclicking Type C when Mining

### ISSUE THREAD

**Issue by JoeProKill2000** [funkemunky/Iris-Issues#95]
**Describe the bug**
So, basically the same as the last bug report, bug when players mine (efficiency 1), some are getting type C alerts. The player recorded is not autoclicking, and it is saying he is.

**Version Information**
Iris Anticheat 1.8.2
Atlas Version 1.1.4.1
Bukkit/Spigot Version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Are you using the ViaVersion plugin?**
Yes

**Server Logs**
N/A

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) He mined
2) It said he was hacking

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.
https://www.mediafire.com/file/u2uq6zsl97hie5v/Minecraft_1.12.2_4_11_2019_4_48_22_PM.mp4/file

**Additional context**
It did not go off for me but I didnt mine as long as he did so u may have to mine for a bit before it starts saying. Also, I don't know whether he was holding down left-click or holding, letting it mine, then stopping.

**Comment by FozzieHi** [comment]
I already said, this is fixed in the next update - why reopen another issue?

**Comment by JoeProKill2000** [comment]
I found a Type C alert, the last one was Type A
