### ISSUE TITLE
Bad Packets Type F when essentials flyspeed is high

### ISSUE THREAD

**Issue by JoeProKill2000** [funkemunky/Iris-Issues#96]
**Describe the bug**
If u up ur flyspeed with essentials, then hold control and fly around, it counts as bad packets type F. If u go to fly speed 10 and hold control, u basically cant fly.

**Version Information**
Iris Anticheat 1.8.2
Atlas Version 1.1.4.1
Bukkit/Spigot Version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Are you using the ViaVersion plugin?**
yes

**Server Logs**
Provide the server log of the time the bug occurred.
N/A

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I uped my speed to 5
2) I held control and flew around.
3) It tp'd me down and said Bad Packets Type F.
4) I uped my speed to 10.
5) I held control and started flying.
6) TONS OF ALERTS

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.
https://www.mediafire.com/file/47web1cidbbon8d/Minecraft_1.12.2_4_11_2019_4_56_46_PM.mp4/file

**Additional context**
Will only happen with increased fly speed and ur holding control and above the ground.

**Comment by FozzieHi** [comment]
I'll take a look at this later, thanks for the report!

**Comment by FozzieHi** [comment]
This should be fixed now.
