### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by CruelWinter2** [funkemunky/Iris-Issues#98]
**Describe the bug**
A clear and concise description of what the bug is. Ground spoofing false flag

**Version Information**
- Iris Anticheat Version (Latest is not a version): 1.8,5
- Atlas Version (Latest is not a version): 1.2 pre-b8
- Bukkit/Spigot Version (Latest is not a version): spigot 1.8.8

**Are you using the ViaVersion plugin?**: yes

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1. Use /tp or a /rtp plugin. I used BetterRTP.
2. Type /rtp

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem. https://drive.google.com/file/d/1fmuVLl_bVNIdJCqdWl-cFaLO54nVCTqD/view?usp=drivesdk

**Comment by kermandev** [comment]
@CruelWinter2 a idea would be to give them a bypass for a short time

**Comment by FozzieHi** [comment]
@CruelWinter2 what flags then?

**Comment by ZakShearman** [comment]
Ground Spoof I believe (as in the video).

**Comment by ZakShearman** [comment]
Seems to happen until the chunk is loaded.

**Comment by FozzieHi** [comment]
This seems to be an issue with the plugin itself, is there a reason it places you into that void when it's counting down? or is that just the chunk being loaded?

**Comment by CruelWinter2** [comment]
It’s just the chunk being loaded.

**Comment by CruelWinter2** [comment]
The same thing happens when I run /tp from a different world.

**Comment by FozzieHi** [comment]
I'm really not sure how I'd fix this on my end, maybe your RTP plugin could use the API and cancel GroundSpoof flags when tped.
