### ISSUE TITLE
Flight B Bug Report

### ISSUE THREAD

**Issue by NotHappyxd** [funkemunky/Iris-Issues#99]
**Describe the bug**

I made a grappling hook plugin that sets your velocity but it flags Flight (B) And Velocity (A)

**Version Information**
- Iris Anticheat Version (Latest is not a version): Idk but its from (4-26-2019 8:26 AM)
- Atlas Version (Latest is not a version): 1.2-PRE-b8
- Bukkit/Spigot Version (Latest is not a version): 1.7.10

**Are you using the ViaVersion plugin?**: 
Nah

**Server Logs (Pastebin link)**
No Errors

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Put in this plugin
2) Do /gh give
3) Throw it.
4) Bring it back and it launches you

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.
https://gyazo.com/ebfe4174fe4e5cf0791beb2a66ddd5b9

**Additional context**

**Comment by HappyTNTguy** [comment]
https://www.mediafire.com/file/z7su7y4q2jnjjh3/GrapplingHook.jar/file

**Comment by NotHappyxd** [comment]
https://www.mediafire.com/file/mcn5fo5vrvbfvcm/GrapplingHook.jar/file

**Comment by FozzieHi** [comment]
You can use the IrisCheatEvent API to cancel if they're using a grappling hook.

**Comment by HappyTNTguy** [comment]
Pardon me if this is stupid im new to coding, do I do

@EventHandler
public void cheatEvent(IrisCheatEvent e) {

e.setCancelled(true);

}

**Comment by NotHappyxd** [comment]
How would I do this?

**Comment by FozzieHi** [comment]
Put Iris.jar into your build path and just cancel the IrisCheatEvent if the player is using a grappling hook.

**Comment by NotHappyxd** [comment]
like I know that but im wondering about the code.

**Comment by NotHappyxd** [comment]
I did 
@EventHandler (priority = EventPriority.HIGHEST)
    public void fishEvent(PlayerFishEvent event, IrisCheatEvent e1) //called before projectileLaunchEvent
    {
        Player player = event.getPlayer();

        if(HookAPI.isGrapplingHook(player.getItemInHand()) == false)
        	return;

		if(event.getState() == org.bukkit.event.player.PlayerFishEvent.State.IN_GROUND  || event.getState() == org.bukkit.event.player.PlayerFishEvent.State.FAILED_ATTEMPT){

        	Location loc = event.getHook().getLocation();
        	
			if(GrapplingHook.usePerms == false || player.hasPermission("grapplinghook.pull.self")){
				PlayerGrappleEvent e = new PlayerGrappleEvent(player, player, loc);
				plugin.getServer().getPluginManager().callEvent(e);
				e1.setCancelled(true);
			}
        }
        else if(event.getState() == org.bukkit.event.player.PlayerFishEvent.State.CAUGHT_ENTITY){
        	event.setCancelled(true);
        	if(event.getCaught() instanceof Player){
        		Player hooked = (Player)event.getCaught();
        	}
        }
        else if(event.getState() == org.bukkit.event.player.PlayerFishEvent.State.CAUGHT_FISH){
        	event.setCancelled(true);
        }
    }

but it cancells the grappling hook

**Comment by FozzieHi** [comment]
Create a Discord ticket, probably easier than talking here.
